language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq bison flex libgmp-dev libmpfr-dev libmpc-dev
script: ./travis-build.sh
branches:
  only:
    - master
notifications:
  recipients:
    - redbrain@gcc.gnu.org
  email:
    on_success: change
    on_failure: always
