// P3074R7 - trivial unions (was std::uninitialized<T>)
// { dg-do compile { target c++26 } }
// { dg-additional-options "-freflection" }

#include <meta>
#include <ranges>

using namespace std::meta;
constexpr auto ctx = std::meta::access_context::unchecked ();
union A { int a; const int b; };
static_assert (is_default_constructible_type (^^A));
static_assert (is_trivially_default_constructible_type (^^A));
static_assert (is_destructible_type (^^A));
static_assert (is_trivially_destructible_type (^^A));
constexpr auto Actor = (members_of (^^A, ctx) | std::views::filter (is_default_constructor) | std::ranges::to <std::vector> ())[0];
constexpr auto Adtor = (members_of (^^A, ctx) | std::views::filter (is_destructor) | std::ranges::to <std::vector> ())[0];
static_assert (is_defaulted (Actor) && !is_deleted (Actor));
static_assert (is_defaulted (Adtor) && !is_deleted (Adtor));
struct B { int a; union { int b; const int c; }; };
static_assert (is_default_constructible_type (^^B));
static_assert (is_trivially_default_constructible_type (^^B));
static_assert (is_destructible_type (^^B));
static_assert (is_trivially_destructible_type (^^B));
constexpr auto Bctor = (members_of (^^B, ctx) | std::views::filter (is_default_constructor) | std::ranges::to <std::vector> ())[0];
constexpr auto Bdtor = (members_of (^^B, ctx) | std::views::filter (is_destructor) | std::ranges::to <std::vector> ())[0];
static_assert (is_defaulted (Bctor) && !is_deleted (Bctor));
static_assert (is_defaulted (Bdtor) && !is_deleted (Bdtor));
union C { const int a = 42; const long b; ~C (); };
static_assert (is_default_constructible_type (^^C));
static_assert (!is_trivially_default_constructible_type (^^C));
static_assert (is_destructible_type (^^C));
static_assert (!is_trivially_destructible_type (^^C));
constexpr auto Cctor = (members_of (^^C, ctx) | std::views::filter (is_default_constructor) | std::ranges::to <std::vector> ())[0];
constexpr auto Cdtor = (members_of (^^C, ctx) | std::views::filter (is_destructor) | std::ranges::to <std::vector> ())[0];
static_assert (is_defaulted (Cctor) && !is_deleted (Cctor));
static_assert (!is_defaulted (Cdtor) && !is_deleted (Cdtor));
struct D { D () = delete; D (int); ~D () = default; };
union E { D a = 42; D b; ~E (); };
static_assert (is_default_constructible_type (^^E));
static_assert (is_destructible_type (^^E));
constexpr auto Ector = (members_of (^^E, ctx) | std::views::filter (is_default_constructor) | std::ranges::to <std::vector> ())[0];
constexpr auto Edtor = (members_of (^^E, ctx) | std::views::filter (is_destructor) | std::ranges::to <std::vector> ())[0];
static_assert (is_defaulted (Ector) && !is_deleted (Ector));
static_assert (!is_defaulted (Edtor) && !is_deleted (Edtor));
struct F { int a; union { D b = 42; D c; }; };
static_assert (is_default_constructible_type (^^F));
static_assert (is_destructible_type (^^F));
constexpr auto Fctor = (members_of (^^F, ctx) | std::views::filter (is_default_constructor) | std::ranges::to <std::vector> ())[0];
constexpr auto Fdtor = (members_of (^^F, ctx) | std::views::filter (is_destructor) | std::ranges::to <std::vector> ())[0];
static_assert (is_defaulted (Fctor) && !is_deleted (Fctor));
static_assert (is_defaulted (Fdtor) && !is_deleted (Fdtor));
struct G { G (); ~G (); };
union I { int a; const int b; ~I (); };
static_assert (is_default_constructible_type (^^I));
static_assert (!is_trivially_default_constructible_type (^^I));
static_assert (is_destructible_type (^^I));
static_assert (!is_trivially_destructible_type (^^I));
constexpr auto Ictor = (members_of (^^I, ctx) | std::views::filter (is_default_constructor) | std::ranges::to <std::vector> ())[0];
constexpr auto Idtor = (members_of (^^I, ctx) | std::views::filter (is_destructor) | std::ranges::to <std::vector> ())[0];
static_assert (is_defaulted (Ictor) && !is_deleted (Ictor));
static_assert (!is_defaulted (Idtor) && !is_deleted (Idtor));
union J { D a; int b; };
static_assert (is_default_constructible_type (^^J));
static_assert (is_trivially_default_constructible_type (^^J));
static_assert (is_destructible_type (^^J));
static_assert (is_trivially_destructible_type (^^J));
constexpr auto Jctor = (members_of (^^J, ctx) | std::views::filter (is_default_constructor) | std::ranges::to <std::vector> ())[0];
constexpr auto Jdtor = (members_of (^^J, ctx) | std::views::filter (is_destructor) | std::ranges::to <std::vector> ())[0];
static_assert (is_defaulted (Jctor) && !is_deleted (Jctor));
static_assert (is_defaulted (Jdtor) && !is_deleted (Jdtor));
union K { G a; int b; };
static_assert (is_default_constructible_type (^^K));
static_assert (is_trivially_default_constructible_type (^^K));
static_assert (is_destructible_type (^^K));
static_assert (is_trivially_destructible_type (^^K));
constexpr auto Kctor = (members_of (^^K, ctx) | std::views::filter (is_default_constructor) | std::ranges::to <std::vector> ())[0];
constexpr auto Kdtor = (members_of (^^K, ctx) | std::views::filter (is_destructor) | std::ranges::to <std::vector> ())[0];
static_assert (is_defaulted (Kctor) && !is_deleted (Kctor));
static_assert (is_defaulted (Kdtor) && !is_deleted (Kdtor));
struct L { int a; union { G b; int c; }; };
static_assert (is_default_constructible_type (^^L));
static_assert (is_trivially_default_constructible_type (^^L));
static_assert (is_destructible_type (^^L));
static_assert (is_trivially_destructible_type (^^L));
constexpr auto Lctor = (members_of (^^L, ctx) | std::views::filter (is_default_constructor) | std::ranges::to <std::vector> ())[0];
constexpr auto Ldtor = (members_of (^^L, ctx) | std::views::filter (is_destructor) | std::ranges::to <std::vector> ())[0];
static_assert (is_defaulted (Lctor) && !is_deleted (Lctor));
static_assert (is_defaulted (Ldtor) && !is_deleted (Ldtor));
union M { M (); int a; int b; };
static_assert (is_default_constructible_type (^^M));
static_assert (!is_trivially_default_constructible_type (^^M));
static_assert (is_destructible_type (^^M));
static_assert (is_trivially_destructible_type (^^M));
constexpr auto Mctor = (members_of (^^M, ctx) | std::views::filter (is_default_constructor) | std::ranges::to <std::vector> ())[0];
constexpr auto Mdtor = (members_of (^^M, ctx) | std::views::filter (is_destructor) | std::ranges::to <std::vector> ())[0];
static_assert (!is_defaulted (Mctor) && !is_deleted (Mctor));
static_assert (is_defaulted (Mdtor) && !is_deleted (Mdtor));
union N { N (); int a; G b; };
static_assert (!is_default_constructible_type (^^N));
static_assert (!is_trivially_default_constructible_type (^^N));
static_assert (!is_destructible_type (^^N));
static_assert (!is_trivially_destructible_type (^^N));
constexpr auto Nctor = (members_of (^^N, ctx) | std::views::filter (is_default_constructor) | std::ranges::to <std::vector> ())[0];
constexpr auto Ndtor = (members_of (^^N, ctx) | std::views::filter (is_destructor) | std::ranges::to <std::vector> ())[0];
static_assert (!is_defaulted (Nctor) && !is_deleted (Nctor));
static_assert (is_defaulted (Ndtor) && is_deleted (Ndtor));
struct O { O (); union { int a; int b; }; };
static_assert (is_default_constructible_type (^^O));
static_assert (!is_trivially_default_constructible_type (^^O));
static_assert (is_destructible_type (^^O));
static_assert (is_trivially_destructible_type (^^O));
constexpr auto Octor = (members_of (^^O, ctx) | std::views::filter (is_default_constructor) | std::ranges::to <std::vector> ())[0];
constexpr auto Odtor = (members_of (^^O, ctx) | std::views::filter (is_destructor) | std::ranges::to <std::vector> ())[0];
static_assert (!is_defaulted (Octor) && !is_deleted (Octor));
static_assert (is_defaulted (Odtor) && !is_deleted (Odtor));
struct P { P (); union { int a; G b; }; };
static_assert (!is_default_constructible_type (^^P));
static_assert (!is_trivially_default_constructible_type (^^P));
static_assert (!is_destructible_type (^^P));
static_assert (!is_trivially_destructible_type (^^P));
constexpr auto Pctor = (members_of (^^P, ctx) | std::views::filter (is_default_constructor) | std::ranges::to <std::vector> ())[0];
constexpr auto Pdtor = (members_of (^^P, ctx) | std::views::filter (is_destructor) | std::ranges::to <std::vector> ())[0];
static_assert (!is_defaulted (Pctor) && !is_deleted (Pctor));
static_assert (is_defaulted (Pdtor) && is_deleted (Pdtor));
struct Q { Q (int); union { int a; G b; }; };
static_assert (!is_default_constructible_type (^^Q));
static_assert (!is_trivially_default_constructible_type (^^Q));
static_assert (!is_destructible_type (^^Q));
static_assert (!is_trivially_destructible_type (^^Q));
static_assert ((members_of (^^Q, ctx) | std::views::filter (is_default_constructor) | std::ranges::to <std::vector> ()).size () == 0);
constexpr auto Qdtor = (members_of (^^Q, ctx) | std::views::filter (is_destructor) | std::ranges::to <std::vector> ())[0];
static_assert (is_defaulted (Qdtor) && is_deleted (Qdtor));
struct R { R () = default; R (int); union { int a; G b; }; };
static_assert (!is_default_constructible_type (^^R));
static_assert (!is_trivially_default_constructible_type (^^R));
static_assert (!is_destructible_type (^^R));
static_assert (!is_trivially_destructible_type (^^R));
constexpr auto Rctor = (members_of (^^R, ctx) | std::views::filter (is_default_constructor) | std::ranges::to <std::vector> ())[0];
constexpr auto Rdtor = (members_of (^^R, ctx) | std::views::filter (is_destructor) | std::ranges::to <std::vector> ())[0];
static_assert (is_defaulted (Rctor) && !is_deleted (Rctor));
static_assert (is_defaulted (Rdtor) && is_deleted (Rdtor));
struct S { S (int); ~S (); };
union T { T (); int a; int b = 42; };
static_assert (is_default_constructible_type (^^T));
static_assert (!is_trivially_default_constructible_type (^^T));
static_assert (is_destructible_type (^^T));
static_assert (is_trivially_destructible_type (^^T));
constexpr auto Tctor = (members_of (^^T, ctx) | std::views::filter (is_default_constructor) | std::ranges::to <std::vector> ())[0];
constexpr auto Tdtor = (members_of (^^T, ctx) | std::views::filter (is_destructor) | std::ranges::to <std::vector> ())[0];
static_assert (!is_defaulted (Tctor) && !is_deleted (Tctor));
static_assert (is_defaulted (Tdtor) && !is_deleted (Tdtor));
union U { U (); int a; S b = 42; };
static_assert (!is_default_constructible_type (^^U));
static_assert (!is_trivially_default_constructible_type (^^U));
static_assert (!is_destructible_type (^^U));
static_assert (!is_trivially_destructible_type (^^U));
constexpr auto Uctor = (members_of (^^U, ctx) | std::views::filter (is_default_constructor) | std::ranges::to <std::vector> ())[0];
constexpr auto Udtor = (members_of (^^U, ctx) | std::views::filter (is_destructor) | std::ranges::to <std::vector> ())[0];
static_assert (!is_defaulted (Uctor) && !is_deleted (Uctor));
static_assert (is_defaulted (Udtor) && is_deleted (Udtor));
struct V { V (); union { int a; int b = 42; }; };
static_assert (is_default_constructible_type (^^V));
static_assert (!is_trivially_default_constructible_type (^^V));
static_assert (is_destructible_type (^^V));
static_assert (is_trivially_destructible_type (^^V));
constexpr auto Vctor = (members_of (^^V, ctx) | std::views::filter (is_default_constructor) | std::ranges::to <std::vector> ())[0];
constexpr auto Vdtor = (members_of (^^V, ctx) | std::views::filter (is_destructor) | std::ranges::to <std::vector> ())[0];
static_assert (!is_defaulted (Vctor) && !is_deleted (Vctor));
static_assert (is_defaulted (Vdtor) && !is_deleted (Vdtor));
struct W { W (); union { int a; S b = 42; }; };
static_assert (!is_default_constructible_type (^^W));
static_assert (!is_trivially_default_constructible_type (^^W));
static_assert (!is_destructible_type (^^W));
static_assert (!is_trivially_destructible_type (^^W));
constexpr auto Wctor = (members_of (^^W, ctx) | std::views::filter (is_default_constructor) | std::ranges::to <std::vector> ())[0];
constexpr auto Wdtor = (members_of (^^W, ctx) | std::views::filter (is_destructor) | std::ranges::to <std::vector> ())[0];
static_assert (!is_defaulted (Wctor) && !is_deleted (Wctor));
static_assert (is_defaulted (Wdtor) && is_deleted (Wdtor));
struct X { X (int); union { int a; S b = 42; }; };
static_assert (!is_default_constructible_type (^^X));
static_assert (!is_trivially_default_constructible_type (^^X));
static_assert (!is_destructible_type (^^X));
static_assert (!is_trivially_destructible_type (^^X));
static_assert ((members_of (^^X, ctx) | std::views::filter (is_default_constructor) | std::ranges::to <std::vector> ()).size () == 0);
constexpr auto Xdtor = (members_of (^^X, ctx) | std::views::filter (is_destructor) | std::ranges::to <std::vector> ())[0];
static_assert (is_defaulted (Xdtor) && is_deleted (Xdtor));
struct Y { Y () = default; Y (int); union { int a; S b = 42; }; };
static_assert (!is_default_constructible_type (^^Y));
static_assert (!is_trivially_default_constructible_type (^^Y));
static_assert (!is_destructible_type (^^Y));
static_assert (!is_trivially_destructible_type (^^Y));
constexpr auto Yctor = (members_of (^^Y, ctx) | std::views::filter (is_default_constructor) | std::ranges::to <std::vector> ())[0];
constexpr auto Ydtor = (members_of (^^Y, ctx) | std::views::filter (is_destructor) | std::ranges::to <std::vector> ())[0];
static_assert (is_defaulted (Yctor) && !is_deleted (Yctor));
static_assert (is_defaulted (Ydtor) && is_deleted (Ydtor));
union AA { AA (); int a; long b; };
static_assert (is_default_constructible_type (^^AA));
static_assert (!is_trivially_default_constructible_type (^^AA));
static_assert (is_destructible_type (^^AA));
static_assert (is_trivially_destructible_type (^^AA));
constexpr auto AActor = (members_of (^^AA, ctx) | std::views::filter (is_default_constructor) | std::ranges::to <std::vector> ())[0];
constexpr auto AAdtor = (members_of (^^AA, ctx) | std::views::filter (is_destructor) | std::ranges::to <std::vector> ())[0];
static_assert (!is_defaulted (AActor) && !is_deleted (AActor));
static_assert (is_defaulted (AAdtor) && !is_deleted (AAdtor));
struct AB { AB () = default; AB (const AB &) = default; int a; ~AB (); };
union AC { AC (); int a; AB b; };
static_assert (!is_default_constructible_type (^^AC));
static_assert (!is_trivially_default_constructible_type (^^AC));
static_assert (!is_destructible_type (^^AC));
static_assert (!is_trivially_destructible_type (^^AC));
constexpr auto ACctor = (members_of (^^AC, ctx) | std::views::filter (is_default_constructor) | std::ranges::to <std::vector> ())[0];
constexpr auto ACdtor = (members_of (^^AC, ctx) | std::views::filter (is_destructor) | std::ranges::to <std::vector> ())[0];
static_assert (!is_defaulted (ACctor) && !is_deleted (ACctor));
static_assert (is_defaulted (ACdtor) && is_deleted (ACdtor));
