[package]
name = "std_detect"
version = "0.1.5"
authors = [
    "Alex Crichton <alex@alexcrichton.com>",
    "Andrew Gallant <jamslam@gmail.com>",
    "Gonzalo Brito Gadeschi <gonzalobg88@gmail.com>",
]
description = "`std::detect` - Rust's standard library run-time CPU feature detection."
documentation = "https://docs.rs/std_detect"
homepage = "https://github.com/rust-lang/stdarch"
repository = "https://github.com/rust-lang/stdarch"
readme = "README.md"
keywords = ["std", "run-time", "feature", "detection"]
categories = ["hardware-support"]
license = "MIT/Apache-2.0"
edition = "2018"

[badges]
is-it-maintained-issue-resolution = { repository = "rust-lang/stdarch" }
is-it-maintained-open-issues = { repository = "rust-lang/stdarch" }
maintenance = { status = "experimental" }

[dependencies]
libc = { version = "0.2", optional = true, default-features = false }
cfg-if = "0.1.10"

[dev-dependencies]
auxv = "0.3.3"
cupid = "0.6.0"

[features]
default = [ "std_detect_dlsym_getauxval", "std_detect_file_io" ]
std_detect_file_io = []
std_detect_dlsym_getauxval = [ "libc" ]
std_detect_env_override = []
