[package]
authors = ["The Rust Project Developers"]
name = "core"
version = "0.0.0"
autotests = false
autobenches = false
edition = "2018"

[lib]
test = false
bench = false

[[test]]
name = "coretests"
path = "tests/lib.rs"

[[bench]]
name = "corebenches"
path = "benches/lib.rs"
test = true

[dev-dependencies]
rand = "0.7"

[features]
# Make panics and failed asserts immediately abort without formatting any message
panic_immediate_abort = []
