[package]
name = "stdarch_examples"
version = "0.0.0"
authors = [
    "Alex Crichton <alex@alexcrichton.com>",
    "Andrew Gallant <jamslam@gmail.com>",
    "Gonzalo Brito Gadeschi <gonzalobg88@gmail.com>",
]
description = "Examples of the stdarch crate."
edition = "2018"

[dependencies]
core_arch = { path = "../crates/core_arch" }
std_detect = { path = "../crates/std_detect" }
quickcheck = "0.9"
rand = "0.7"

[[bin]]
name = "hex"
path = "hex.rs"

[[example]]
name = "wasm"
crate-type = ["cdylib"]
path = "wasm.rs"
