[package]
authors = ["The Rust Project Developers"]
name = "syntax_ext"
version = "0.0.0"
edition = "2018"

[lib]
name = "syntax_ext"
path = "lib.rs"
doctest = false

[dependencies]
fmt_macros = { path = "../libfmt_macros" }
errors = { path = "../librustc_errors", package = "rustc_errors" }
syntax = { path = "../libsyntax" }
syntax_pos = { path = "../libsyntax_pos" }
rustc_data_structures = { path = "../librustc_data_structures" }
rustc_target = { path = "../librustc_target" }
smallvec = { version = "0.6.7", features = ["union", "may_dangle"] }
log = "0.4"
