/* Subroutines for the Rust front end on the AVR architecture.
   Copyright (C) 2020 Free Software Foundation, Inc.

GCC is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3, or (at your option)
any later version.

GCC is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with GCC; see the file COPYING3.  If not see
<http://www.gnu.org/licenses/>.  */

#include "config.h"
#include "system.h"
#include "coretypes.h"
#include "tm.h"
#include "tm_p.h"
#include "rust/rust-target.h"
#include "rust/rust-target-def.h"

/* Target features for AVR0 targets.  */

static void avr_rust_target_features_avr0(void) {}

/* Target features for AVR1 targets.  */

static void avr_rust_target_features_avr1(void) {
    avr_rust_target_features_avr0();
}

/* Target features for AVR2 targets.  */

static void avr_rust_target_features_avr2(void) {
    avr_rust_target_features_avr1();

    rust_add_target_info("target_feature", "sram");

    // GCC seems to imply that this is generated by default. TODO ensure that it is true.
    rust_add_target_info("target_feature", "ijmpcall");

    // GCC seems to imply that SUBI is generated by default, so putting it here for now TODO.
    // BTW, does ADDI even exist? gcc has no record of it, search mentions results saying "why no addi?"
    rust_add_target_info("target_feature", "addsubiw");
}

/* Target features for AVR2.5 targets.  */
static void avr_rust_target_features_avr25(void) {
    avr_rust_target_features_avr2();

    // FIXME: remove if can figure out how to add break based on options
    rust_add_target_info("target_feature", "break");

    // FIXME: remove if can figure out how to add spm based on options
    rust_add_target_info("target_feature", "spm");
}

/* Target features for AVR Tiny targets.  */
static void avr_rust_target_features_avrtiny(void) {
    avr_rust_target_features_avr0();

    // FIXME: remove if can figure out how to add break based on options
    rust_add_target_info("target_feature", "break");

    rust_add_target_info("target_feature", "sram");
}

/* Target features for AVR XMEGA targets. */
static void avr_rust_target_features_avrxmega(void) {
    avr_rust_target_features_avr0();

    // GCC seems to imply that this is generated by default. TODO ensure that it is true.
    rust_add_target_info("target_feature", "ijmpcall");

    // GCC seems to imply that SUBI is generated by default, so putting it here for now TODO.
    // BTW, does ADDI even exist? gcc has no record of it, search mentions results saying "why no addi?"
    rust_add_target_info("target_feature", "addsubiw");

    // FIXME: remove if can figure out how to add break based on options
    rust_add_target_info("target_feature", "break");

    // FIXME: remove if can figure out how to add spm and spmx based on options
    rust_add_target_info("target_feature", "spm");
    rust_add_target_info("target_feature", "spmx");

    // FIXME: remove if can figure out how to add des based on options
    rust_add_target_info("target_feature", "des");

    rust_add_target_info("target_feature", "sram");
}

/* Implement TARGET_RUST_CPU_INFO for AVR targets.  */

void avr_rust_target_cpu_info(void) {
    rust_add_target_info("target_arch", "avr");

    if (strcmp(avr_arch->name, "avr0") == 0)
        avr_rust_target_features_avr0();
    else if (strcmp(avr_arch->name, "avr1") == 0)
        avr_rust_target_features_avr1();
    // special handling for tiny and xmega
    else if (strcmp(avr_arch->name, "avrtiny") == 0)
        avr_rust_target_features_avrtiny();
    else if (strcmp(avr_arch->name, "avrxmega2") == 0)
        avr_rust_target_features_avrxmega();
    else if (strcmp(avr_arch->name, "avrxmega3") == 0)
        avr_rust_target_features_avrxmega();
    else if (strcmp(avr_arch->name, "avrxmega4") == 0)
        avr_rust_target_features_avrxmega();
    else if (strcmp(avr_arch->name, "avrxmega5") == 0)
        avr_rust_target_features_avrxmega();
    else if (strcmp(avr_arch->name, "avrxmega6") == 0)
        avr_rust_target_features_avrxmega();
    else if (strcmp(avr_arch->name, "avrxmega7") == 0)
        avr_rust_target_features_avrxmega();
    else if (strcmp(avr_arch->name, "avr2") == 0)
        avr_rust_target_features_avr2();
    else if (strcmp(avr_arch->name, "avr25") == 0)
        avr_rust_target_features_avr25();
    else if (strcmp(avr_arch->name, "avr35") == 0)
        avr_rust_target_features_avr25();
    else if (strcmp(avr_arch->name, "avr4") == 0)
        avr_rust_target_features_avr25();
    else if (strcmp(avr_arch->name, "avr5") == 0)
        avr_rust_target_features_avr25();
    else if (strcmp(avr_arch->name, "avr51") == 0)
        avr_rust_target_features_avr25();
    else if (strcmp(avr_arch->name, "avr6") == 0)
        avr_rust_target_features_avr25();
    else
        avr_rust_target_features_avr2();
    // default to basing on avr2

    if (AVR_HAVE_JMP_CALL)
        rust_add_target_info("target_feature", "jmpcall");
    if (AVR_HAVE_EIJMP_EICALL)
        rust_add_target_info("target_feature", "eijmpcall");

    /* from what i can tell so far, gcc generates IJMP if EIJMP is not enabled or something. llvm does not
     * seem to treat it that way. As such, I'll leave both on if both are available. */

    if (AVR_HAVE_8BIT_SP)
        rust_add_target_info("target_feature", "smallstack");
    if (AVR_HAVE_MOVW)
        rust_add_target_info("target_feature", "movw");
    if (AVR_HAVE_LPM)
        rust_add_target_info("target_feature", "lpm");
    if (AVR_HAVE_LPMX)
        rust_add_target_info("target_feature", "lpmx");
    if (AVR_HAVE_ELPM)
        rust_add_target_info("target_feature", "elpm");
    if (AVR_HAVE_ELPMX)
        rust_add_target_info("target_feature", "elpmx");
    if (TARGET_RMW)
        rust_add_target_info("target_feature", "rmw");   
    if (AVR_HAVE_MUL)
        rust_add_target_info("target_feature", "mul");
    
    // i think this is what llvm means by "Tiny core specific instruction encodings", but TODO ensure it
    if (AVR_TINY)
        rust_add_target_info("target_feature", "tinyencoding");
    
    if (AVR_XMEGA) {

    } else {
        /* TODO: could not find gcc equivalent of determining whether "memory-mapped registers" occurs. 
         * However, it appears to only not occur in xmega and xmegau cpus. so test on that for now. */
        rust_add_target_info("target_feature", "memmappedregs");
    }
    
    // TODO: find if "spm" (SPM insn) is in GCC - can't seem to find it, along with "spmx" (SPM Z+)
    // TODO: add "des" (DES instruction) if GCC has it - it does not appear to be in gcc
    // TODO: add "break" (BREAK instruction) if GCC has it - it does not appear to be in gcc
}
