// Copyright (C) 2025 Free Software Foundation, Inc.

// This file is part of GCC.

// GCC is free software; you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation; either version 3, or (at your option) any later
// version.

// GCC is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.

// You should have received a copy of the GNU General Public License
// along with GCC; see the file COPYING3.  If not see
// <http://www.gnu.org/licenses/>.

// This header contains a list of concrete classes visitable using ASTVisitor

// rust-ast.h
VISIT (Token)
VISIT (DelimTokenTree)
VISIT (AttrInputMetaItemContainer)
VISIT (IdentifierExpr)
VISIT (Lifetime)
VISIT (LifetimeParam)

// rust-path.h
VISIT (ConstGenericParam)
VISIT (PathInExpression)
VISIT (TypePathSegment)
VISIT (TypePathSegmentGeneric)
VISIT (TypePathSegmentFunction)
VISIT (TypePath)
VISIT (QualifiedPathInExpression)
VISIT (QualifiedPathInType)

// rust-expr.h
VISIT (LiteralExpr)
VISIT (AttrInputLiteral)
VISIT (AttrInputMacro)
VISIT (MetaItemLitExpr)
VISIT (MetaItemPathLit)
VISIT (BorrowExpr)
VISIT (DereferenceExpr)
VISIT (ErrorPropagationExpr)
VISIT (NegationExpr)
VISIT (ArithmeticOrLogicalExpr)
VISIT (ComparisonExpr)
VISIT (LazyBooleanExpr)
VISIT (TypeCastExpr)
VISIT (AssignmentExpr)
VISIT (CompoundAssignmentExpr)
VISIT (GroupedExpr)
VISIT (ArrayElemsValues)
VISIT (ArrayElemsCopied)
VISIT (ArrayExpr)
VISIT (ArrayIndexExpr)
VISIT (TupleExpr)
VISIT (TupleIndexExpr)
VISIT (StructExprStruct)
VISIT (StructExprFieldIdentifier)
VISIT (StructExprFieldIdentifierValue)
VISIT (StructExprFieldIndexValue)
VISIT (StructExprStructFields)
VISIT (StructExprStructBase)
VISIT (CallExpr)
VISIT (MethodCallExpr)
VISIT (FieldAccessExpr)
VISIT (ClosureExprInner)
VISIT (BlockExpr)
VISIT (AnonConst)
VISIT (ConstBlock)
VISIT (ClosureExprInnerTyped)
VISIT (ContinueExpr)
VISIT (BreakExpr)
VISIT (RangeFromToExpr)
VISIT (RangeFromExpr)
VISIT (RangeToExpr)
VISIT (RangeFullExpr)
VISIT (RangeFromToInclExpr)
VISIT (RangeToInclExpr)
VISIT (ReturnExpr)
VISIT (TryExpr)
VISIT (BoxExpr)
VISIT (UnsafeBlockExpr)
VISIT (LoopExpr)
VISIT (WhileLoopExpr)
VISIT (WhileLetLoopExpr)
VISIT (ForLoopExpr)
VISIT (IfExpr)
VISIT (IfExprConseqElse)
VISIT (IfLetExpr)
VISIT (IfLetExprConseqElse)
VISIT (MatchExpr)
VISIT (AwaitExpr)
VISIT (AsyncBlockExpr)
VISIT (InlineAsm)
VISIT (LlvmInlineAsm)

// rust-item.h
VISIT (TypeParam)
VISIT (SelfParam)
VISIT (FunctionParam)
VISIT (VariadicParam)
VISIT (LifetimeWhereClauseItem)
VISIT (TypeBoundWhereClauseItem)
VISIT (Module)
VISIT (ExternCrate)
VISIT (UseTreeGlob)
VISIT (UseTreeList)
VISIT (UseTreeRebind)
VISIT (UseDeclaration)
VISIT (Function)
VISIT (TypeAlias)
VISIT (StructStruct)
VISIT (TupleStruct)
VISIT (EnumItem)
VISIT (EnumItemTuple)
VISIT (EnumItemStruct)
VISIT (EnumItemDiscriminant)
VISIT (Enum)
VISIT (Union)
VISIT (ConstantItem)
VISIT (StaticItem)
VISIT (TraitItemConst)
VISIT (TraitItemType)
VISIT (Trait)
VISIT (InherentImpl)
VISIT (TraitImpl)
VISIT (ExternalTypeItem)
VISIT (ExternalStaticItem)
VISIT (ExternBlock)

// rust-macro.h
VISIT (MacroMatchFragment)
VISIT (MacroMatchRepetition)
VISIT (MacroMatcher)
VISIT (MacroRulesDefinition)
VISIT (MacroInvocation)
VISIT (MetaItemPath)
VISIT (MetaItemSeq)
VISIT (MetaWord)
VISIT (MetaNameValueStr)
VISIT (MetaListPaths)
VISIT (MetaListNameValueStr)

// rust-pattern.h
VISIT (LiteralPattern)
VISIT (IdentifierPattern)
VISIT (WildcardPattern)
VISIT (RestPattern)
VISIT (RangePatternBoundLiteral)
VISIT (RangePatternBoundPath)
VISIT (RangePatternBoundQualPath)
VISIT (RangePattern)
VISIT (ReferencePattern)
VISIT (StructPatternFieldTuplePat)
VISIT (StructPatternFieldIdentPat)
VISIT (StructPatternFieldIdent)
VISIT (StructPattern)
VISIT (TupleStructItemsNoRange)
VISIT (TupleStructItemsRange)
VISIT (TupleStructPattern)
VISIT (TuplePatternItemsMultiple)
VISIT (TuplePatternItemsRanged)
VISIT (TuplePattern)
VISIT (GroupedPattern)
VISIT (SlicePattern)
VISIT (AltPattern)

// rust-stmt.h
VISIT (EmptyStmt)
VISIT (LetStmt)
VISIT (ExprStmt)

// rust-type.h
VISIT (TraitBound)
VISIT (ImplTraitType)
VISIT (TraitObjectType)
VISIT (ParenthesisedType)
VISIT (ImplTraitTypeOneBound)
VISIT (TraitObjectTypeOneBound)
VISIT (TupleType)
VISIT (NeverType)
VISIT (RawPointerType)
VISIT (ReferenceType)
VISIT (ArrayType)
VISIT (SliceType)
VISIT (InferredType)
VISIT (BareFunctionType)

// rust-builtin-ast-nodes.h
VISIT (FormatArgs)
