name: Clang Format Lint

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: 'gcc/rust/'
        extensions: 'h,cc'
        clangFormatVersion: 10
