name: Clang-Format

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.5
      with:
        source: './gcc/rust/'
        exclude: './third_party'
        clangFormatVersion: 9
