name: GNU Commit Format Checker

on:
  pull_request:
    branches:
      - master
      - gcc-patch-dev

jobs:
  check_commit_formats:
    runs-on: ubuntu-latest
    name: Commits Check
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Install Deps
        run: |
          sudo apt-get update;
          sudo apt-get install -y \
            python3 \
            python3-git
      
      - name: GCC check PR Commits
        run: |
          retval=0
          if ! python3 contrib/gcc-changelog/git_check_commit.py origin/${{ github.event.pull_request.base.ref }}..${{ github.event.pull_request.head.sha }}; then
            retval=1
          fi
          for commit in $(git rev-list origin/${{ github.event.pull_request.base.ref }}..${{ github.event.pull_request.head.sha }});
          do
            echo -n "Checking gccrs prefix for $commit: "
            if [[ $(git log -1 --format="%s" $commit) = gccrs:* ]]; then
              echo "OK"
            else
              retval=1
              echo "KO"
            fi
          done
          exit $retval
     
