name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for your contribution fellow Rustacean'
        pr-message: 'Thanks for your contribution, please be aware that this project is destined to be upstreamed to GCC. This will require copyright assignment, see https://gcc.gnu.org/contribute.html'
