/*  DO NOT EDIT THIS FILE.

    It has been auto-edited by fixincludes from:

	"fixinc/tests/inc/sys/int_types.h"

    This had to be done to correct non-standard usages in the
    original, manufacturer supplied header file.  */



#if defined( SOLARIS_INT8_T_CHECK )
#if !defined(_LEGACY_INT8_T)
typedef signed char int8_t;
#else
typedef char int8_t;
#endif
#if !defined(_LEGACY_INT8_T)
typedef signed char int_fast8_t;
#else
typedef char int_fast8_t;
#endif
#if !defined(_LEGACY_INT8_T)
typedef signed char int_least8_t;
#else
typedef char int_least8_t;
#endif
#endif  /* SOLARIS_INT8_T_CHECK */
